"use client";

import { useState, useRef, useEffect } from "react";
import { api } from "@/lib/api"; // Adjust import path if needed (e.g., "../../lib/api")

interface Message {
  id: string;
  sender: "user" | "analyst";
  text: string;
  timestamp: string;
}

const PRESET_PROMPTS = [
  "Summarize air quality anomalies detected in the past 24 hours.",
  "Which monitoring zone currently exhibits the highest PM2.5 levels?",
  "Generate a forecast report for London GR9 over the next 6 hours.",
];

export default function AIAnalystPage() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      sender: "analyst",
      text: "Hello! I am AirSentinel AI Analyst. Ask me about real-time sensor streams, spatial anomaly patterns, or predictive air quality models.",
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    },
  ]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleSend = async (textToSend?: string) => {
    const queryText = textToSend || input;
    if (!queryText.trim() || isLoading) return;

    const userMsg: Message = {
      id: Date.now().toString(),
      sender: "user",
      text: queryText,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    };

    setMessages((prev) => [...prev, userMsg]);
    if (!textToSend) setInput("");
    setIsLoading(true);

    try {
      // Utilizing centralized api client helper which handles airsentinel_token automatically
      const data = await api.askAgent(queryText);

      const analystMsg: Message = {
        id: (Date.now() + 1).toString(),
        sender: "analyst",
        text: data.response || data.message || data.output || "No response generated by the agent.",
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };

      setMessages((prev) => [...prev, analystMsg]);
    } catch (err: any) {
      const errorMsg: Message = {
        id: (Date.now() + 1).toString(),
        sender: "analyst",
        text: `⚠️ Error reaching AI Agent: ${err.message || "Failed to process request."}`,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-[calc(100vh-2rem)] p-6 space-y-4 text-slate-100">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">AI Environmental Analyst</h1>
          <p className="text-slate-400 text-sm">Natural language querying for sensor insights & predictive intelligence</p>
        </div>
        <span className="px-3 py-1 text-xs font-semibold rounded-full bg-emerald-950/80 text-emerald-400 border border-emerald-700/60">
          Agent Active
        </span>
      </div>

      {/* Messages Stream */}
      <div className="flex-1 overflow-y-auto space-y-4 pr-2">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex ${msg.sender === "user" ? "justify-end" : "justify-start"}`}
          >
            <div
              className={`max-w-[80%] rounded-2xl px-4 py-3 shadow-md text-sm leading-relaxed ${
                msg.sender === "user"
                  ? "bg-teal-600 text-white rounded-br-none"
                  : "bg-slate-900 border border-slate-800 text-slate-200 rounded-bl-none"
              }`}
            >
              <div className="whitespace-pre-line font-sans">{msg.text}</div>
              <div
                className={`text-[10px] mt-1.5 text-right ${
                  msg.sender === "user" ? "text-teal-200" : "text-slate-500"
                }`}
              >
                {msg.timestamp}
              </div>
            </div>
          </div>
        ))}

        {isLoading && (
          <div className="flex justify-start">
            <div className="bg-slate-900 border border-slate-800 rounded-2xl rounded-bl-none px-4 py-3 text-slate-400 text-sm flex items-center space-x-2">
              <span className="h-2 w-2 bg-teal-400 rounded-full animate-bounce" />
              <span className="h-2 w-2 bg-teal-400 rounded-full animate-bounce [animation-delay:0.2s]" />
              <span className="h-2 w-2 bg-teal-400 rounded-full animate-bounce [animation-delay:0.4s]" />
              <span className="ml-2 text-xs">Analyzing spatial sensors...</span>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Preset Prompts */}
      <div className="flex gap-2 overflow-x-auto pb-1">
        {PRESET_PROMPTS.map((prompt, idx) => (
          <button
            key={idx}
            onClick={() => handleSend(prompt)}
            disabled={isLoading}
            className="text-xs bg-slate-900 hover:bg-slate-800 border border-slate-800 rounded-lg px-3 py-1.5 text-slate-300 transition whitespace-nowrap disabled:opacity-50"
          >
            💡 {prompt}
          </button>
        ))}
      </div>

      {/* Input Box */}
      <form
        onSubmit={(e) => {
          e.preventDefault();
          handleSend();
        }}
        className="flex space-x-2"
      >
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask AI Analyst about sensor logs, forecasts, or anomalies..."
          className="flex-1 bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-sm text-slate-200 focus:outline-none focus:border-teal-500 transition"
        />
        <button
          type="submit"
          disabled={isLoading || !input.trim()}
          className="bg-teal-600 hover:bg-teal-500 text-white font-medium px-5 py-3 rounded-xl text-sm transition disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Send
        </button>
      </form>
    </div>
  );
}